export type CinematicScene = "welcome" | "processing" | "report";

export const CINEMATIC_ASSETS = [
  {
    id: "halo-orbit-primary",
    src: "/assets/cinematic/halo-orbit-primary.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome", "processing"],
    blendMode: "screen",
    opacityRange: [0.14, 0.42],
    remotion: { durationSeconds: 12, delaySeconds: 0, easing: "0.16,1,0.3,1" },
  },
  {
    id: "halo-orbit-offset",
    src: "/assets/cinematic/halo-orbit-offset.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome", "report"],
    blendMode: "screen",
    opacityRange: [0.1, 0.34],
    remotion: { durationSeconds: 14, delaySeconds: 0.4, easing: "0.16,1,0.3,1" },
  },
  {
    id: "halo-orbit-close",
    src: "/assets/cinematic/halo-orbit-close.png",
    width: 2048,
    height: 2048,
    scenes: ["processing"],
    blendMode: "screen",
    opacityRange: [0.16, 0.48],
    remotion: { durationSeconds: 8, delaySeconds: 0.1, easing: "0.65,0,0.35,1" },
  },
  {
    id: "scan-beam-horizontal",
    src: "/assets/cinematic/scan-beam-horizontal.png",
    width: 2160,
    height: 3840,
    scenes: ["processing", "report"],
    blendMode: "screen",
    opacityRange: [0.18, 0.52],
    remotion: { durationSeconds: 3.8, delaySeconds: 0, easing: "0.65,0,0.35,1" },
  },
  {
    id: "scan-beam-vertical",
    src: "/assets/cinematic/scan-beam-vertical.png",
    width: 2160,
    height: 3840,
    scenes: ["processing"],
    blendMode: "screen",
    opacityRange: [0.12, 0.42],
    remotion: { durationSeconds: 5.5, delaySeconds: 0.5, easing: "0.65,0,0.35,1" },
  },
  {
    id: "light-leak-corner-warm",
    src: "/assets/cinematic/light-leak-corner-warm.png",
    width: 3840,
    height: 2160,
    scenes: ["report"],
    blendMode: "screen",
    opacityRange: [0.1, 0.3],
    remotion: { durationSeconds: 16, delaySeconds: 0, easing: "0.16,1,0.3,1" },
  },
  {
    id: "light-leak-drift-vertical",
    src: "/assets/cinematic/light-leak-drift-vertical.png",
    width: 2160,
    height: 3840,
    scenes: ["welcome"],
    blendMode: "screen",
    opacityRange: [0.12, 0.32],
    remotion: { durationSeconds: 18, delaySeconds: 0.2, easing: "0.16,1,0.3,1" },
  },
  {
    id: "serum-droplets-fine",
    src: "/assets/cinematic/serum-droplets-fine.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome", "processing"],
    blendMode: "screen",
    opacityRange: [0.12, 0.34],
    remotion: { durationSeconds: 11, delaySeconds: 0.8, easing: "0.16,1,0.3,1" },
  },
  {
    id: "serum-droplets-near",
    src: "/assets/cinematic/serum-droplets-near.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome"],
    blendMode: "screen",
    opacityRange: [0.08, 0.28],
    remotion: { durationSeconds: 13, delaySeconds: 0.3, easing: "0.16,1,0.3,1" },
  },
  {
    id: "serum-ribbon-arc",
    src: "/assets/cinematic/serum-ribbon-arc.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome", "report"],
    blendMode: "screen",
    opacityRange: [0.1, 0.3],
    remotion: { durationSeconds: 10, delaySeconds: 0.5, easing: "0.16,1,0.3,1" },
  },
  {
    id: "leader-lines-left",
    src: "/assets/cinematic/leader-lines-left.png",
    width: 2048,
    height: 2048,
    scenes: ["report"],
    blendMode: "screen",
    opacityRange: [0.14, 0.44],
    remotion: { durationSeconds: 7, delaySeconds: 0.1, easing: "0.16,1,0.3,1" },
  },
  {
    id: "leader-lines-right",
    src: "/assets/cinematic/leader-lines-right.png",
    width: 2048,
    height: 2048,
    scenes: ["report"],
    blendMode: "screen",
    opacityRange: [0.14, 0.44],
    remotion: { durationSeconds: 7, delaySeconds: 0.25, easing: "0.16,1,0.3,1" },
  },
  {
    id: "face-zone-hairline",
    src: "/assets/cinematic/face-zone-hairline.png",
    width: 2048,
    height: 2048,
    scenes: ["processing", "report"],
    blendMode: "screen",
    opacityRange: [0.16, 0.45],
    remotion: { durationSeconds: 6.5, delaySeconds: 0.2, easing: "0.16,1,0.3,1" },
  },
  {
    id: "micro-texture-glow",
    src: "/assets/cinematic/micro-texture-glow.png",
    width: 2048,
    height: 2048,
    scenes: ["welcome", "report"],
    blendMode: "screen",
    opacityRange: [0.08, 0.24],
    remotion: { durationSeconds: 9, delaySeconds: 0.7, easing: "0.16,1,0.3,1" },
  },
  {
    id: "glass-caustic-wave",
    src: "/assets/cinematic/glass-caustic-wave.png",
    width: 3840,
    height: 2160,
    scenes: ["welcome", "report"],
    blendMode: "screen",
    opacityRange: [0.08, 0.26],
    remotion: { durationSeconds: 15, delaySeconds: 0.6, easing: "0.16,1,0.3,1" },
  },
  {
    id: "edge-vignette-depth",
    src: "/assets/cinematic/edge-vignette-depth.png",
    width: 2160,
    height: 3840,
    scenes: ["welcome", "processing", "report"],
    blendMode: "multiply",
    opacityRange: [0.08, 0.2],
    remotion: { durationSeconds: 20, delaySeconds: 0, easing: "0.16,1,0.3,1" },
  },
] as const;

export type CinematicAsset = (typeof CINEMATIC_ASSETS)[number];
export type CinematicAssetId = CinematicAsset["id"];

export const CINEMATIC_ASSET_MAP = Object.fromEntries(
  CINEMATIC_ASSETS.map((asset) => [asset.id, asset]),
) as Record<CinematicAssetId, CinematicAsset>;

export function getCinematicAssets(scene: CinematicScene) {
  return CINEMATIC_ASSETS.filter((asset) =>
    (asset.scenes as readonly CinematicScene[]).includes(scene),
  );
}
